config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home'

  mount Sidekiq::Web => '/jobs'

  get 'reports/index'

  get 'reports/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "reports#index"

  get "/profiles/report", "profiles#report"

  resources :reports, only: [:index, :show, :destroy] do
    resources :profiles, only: [:index, :show]
    get 'summary', on: :member
  end

  resources :analytics_events do
    post 'fire', on: :member
  end


  post 'import-report', to: 'reports#import'
  post 'import-analytics-logfile', to: 'analytics_events#import_analytics_logfile'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
require 'active_record/diff'

class Profile < ApplicationRecord
  include ActiveRecord::Diff
  diff :platform_id, :card_holder_name, :email,
       :photo, :photo_upload_allowed, :card_number,
       :valid_from, :valid_to, :is_profile_present_on_ccdb

  has_one :sibling, class_name: "Profile"
  after_destroy :destroy_sibling
  belongs_to :report

  attribute :differences

  def destroy_sibling
    sibling&.destroy
  end

  def sibling_difference
    diff sibling
  end

  def differences
    sibling_difference.keys
  end


  def self.import_json_file(file_name = nil, destroy_old = true)
    json = read_json file_name

    import_json(json, destroy_old)
  end

  def self.import_json(json = nil, destroy_old = true)
    Profile.transaction do
      if destroy_old
        report = Report.where(version: json['version']).first
        report&.destroy!
      end
      report = Report.find_or_create_by!(
          version: json['version']
      )

      report.update(
          date: Time.current,
          count: json['total'],
      )

      differences = json['differences']
      logger.info "Found #{differences.count} items"

      differences.each.with_index(1) do |d, i|
        mw = d.dig('mw')
        ccdb = d.dig('ccdb')

        old_profile = nil
        [mw, ccdb].each_with_index do |p, pi|
          next unless p.present?
          profile = Profile.create!(
              platform_id: p.dig('profileId'),
              card_holder_name: p.dig('cardHolderName'),
              email: p.dig('email'),
              photo: p.dig('photo'),
              photo_upload_allowed: p.dig('photoUploadAllowed'),
              card_number: p.dig('cardNumber'),
              valid_to: Time.at(p.dig('validTo').to_i/1000),
              valid_from: Time.at(p.dig('validFrom').to_i/1000),
              is_profile_present_on_ccdb: d.dig('isProfilePresentOnCcdb'),
              platform_name: pi.zero? ? "mw" : "ccdb",
              report: report,
          )

          if pi == 1
            profile.update! sibling: old_profile
            old_profile.update! sibling: profile
          end
          old_profile = profile

        end
        logger.info "Processed #{(i.to_f/differences.count*100).to_s[0..5]}% - #{i} of #{differences.count}" if i%100 == 0

      end
    end

    nil
  end


  private


  def self.destroy_all_profiles!
    logger.warn "Destroying all #{Profile.all.count} profiles in DB"
    Profile.transaction do
      Profile.delete_all
    end
    logger.warn "Done"
  end

  def self.read_json(file_name)
    f_contents = File.read(file_name)
    JSON.parse(f_contents)
  end


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  http_basic_authenticate_with name: Rails.application.secrets.basic_auth_username, password: Rails.application.secrets.basic_auth_password
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @report = Report.find(params[:report_id])
    @q = @report.profiles.ransack(params[:q])
    @profiles = @q.result(distinct: true).includes(:sibling).page(params[:page])
  end


  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html {redirect_to @profile, notice: 'Profile was successfully created.'}
        format.json {render :show, status: :created, location: @profile}
      else
        format.html {render :new}
        format.json {render json: @profile.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html {redirect_to @profile, notice: 'Profile was successfully updated.'}
        format.json {render :show, status: :ok, location: @profile}
      else
        format.html {render :edit}
        format.json {render json: @profile.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html {redirect_to profiles_url, notice: 'Profile was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_profile
    @profile = Profile.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def profile_params
    params.require(:profile).permit(:platform_id, :card_holder_name, :email, :photo, :photo_upload_allowed, :card_number, :valid_from, :valid_to, :is_profile_present_on_ccdb)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def field_color_for(field)
    colors = [:blue, :red, :olive, :brown, :violet, :yellow, :pink, :purple, :orange, :green]
    fields = [:photo, :card_number, :valid_from, :valid_to, :photo_upload_allowed, :card_holder_name, :email]

    colors[fields.index(field)%colors.count].to_s
  end
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :platform_id %>
    <%= form.number_field :platform_id, id: :profile_platform_id %>
  </div>

  <div class="field">
    <%= form.label :card_holder_name %>
    <%= form.text_field :card_holder_name, id: :profile_card_holder_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :profile_email %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo, id: :profile_photo %>
  </div>

  <div class="field">
    <%= form.label :photo_upload_allowed %>
    <%= form.check_box :photo_upload_allowed, id: :profile_photo_upload_allowed %>
  </div>

  <div class="field">
    <%= form.label :card_number %>
    <%= form.text_field :card_number, id: :profile_card_number %>
  </div>

  <div class="field">
    <%= form.label :valid_from %>
    <%= form.datetime_select :valid_from, id: :profile_valid_from %>
  </div>

  <div class="field">
    <%= form.label :valid_to %>
    <%= form.datetime_select :valid_to, id: :profile_valid_to %>
  </div>

  <div class="field">
    <%= form.label :is_profile_present_on_ccdb %>
    <%= form.text_field :is_profile_present_on_ccdb, id: :profile_is_profile_present_on_ccdb %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_search_form.html.erb
<div class="ui raised segment">

  <%= search_form_for(@q, url: report_profiles_path(params[:report_id]),class: "ui form") do |f| %>
      <div class="two fields">
        <div class="field">
          <%= f.label :email_cont %>
          <%= f.search_field :email_cont %>
        </div>

        <div class="field">
          <%= f.label :user_id_eq %>
          <%= f.search_field :platform_id_eq %>
        </div>

      </div>
      <div class="two fields">
        <div class="field">
          <%= f.label :card_number_cont %>
          <%= f.search_field :card_number_cont %>

        </div>

        <div class="field">
          <%= f.label :card_holder_name_or_email_or_photo_or_card_number_cont %>
          <%= f.search_field :card_holder_name_or_email_or_photo_or_card_number_cont %>
        </div>
      </div>
      <%= f.submit class: "ui primary button" %>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Report version <%= @report.version %></h1>


<div class="ui grid">
  <div class="row">
    <div class="three wide column">
      <div class="ui secondary vertical menu">
        <%= link_to "Back to reports", reports_path, class: "item" %>
        <%= link_to "Report summary", summary_report_path(params[:report_id]), class: "item" %>
        <%= link_to "Admin and other Search", '/admin', class: "item" %>
      </div>
    </div>

    <div class="nine wide column">
      <%= render 'profiles/search_form' %>
    </div>
    <div class="three wide column"></div>
  </div>


  <% cache [Profile.all.order(updated_at: :desc).first.updated_at, params.values.map(&:to_s), params.keys.map(&:to_s)] do %>
      <div class="centered row">
        <div class="eight wide column">
          <%= paginate @profiles %>
        </div>
      </div>

      <div class="row">
        <div class="sixteen wide column">
          <div class="ui celled eleven column grid">
            <div class="row">
              <div class="column"><%= sort_link(@q, :platform_id, [:platform_id, platform_name: :asc], "ID") %></div>
              <div class="column">Platform</div>
              <div class="column">Diffs</div>
              <div class="column"><%= sort_link(@q, :card_name, [:card_holder_name, platform_name: :asc], "Card holder name") %></div>
              <div class="column"><%= sort_link(@q, :email) %></div>
              <div class="column"><%= sort_link(@q, :photo) %></div>
              <div class="column">Photo upload allowed</div>
              <div class="column"><%= sort_link(@q, :card_number) %></div>
              <div class="column"><%= sort_link(@q, :valid_from) %></div>
              <div class="column"><%= sort_link(@q, :valid_to) %></div>
              <div class="column">Is profile present on ccdb</div>
            </div>

            <% @profiles.each do |profile| %>
                <div class="row">
                  <div class="column"><%= profile.platform_id %></div>
                  <div class="column"><%= profile.platform_name %></div>
                  <div class="column">
                    <% profile.differences.each_with_index do |diff, index| %>
                      <a class="ui <%= field_color_for(diff) %> label"><%= diff.to_s.humanize %></a>
                    <% end %>

                  </div>
                  <div class="column"><%= link_to(profile.card_holder_name, report_profile_path(params[:report_id], profile)) %></div>
                  <div class="column"><%= profile.email %></div>
                  <div class="column"><%= profile.photo %></div>
                  <div class="column"><%= profile.photo_upload_allowed %></div>
                  <div class="column"><%= profile.card_number %></div>
                  <div class="column"><%= profile.valid_from %></div>
                  <div class="column"><%= profile.valid_to %></div>
                  <div class="column"><%= profile.is_profile_present_on_ccdb %></div>
                </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="centered row">
        <div class="eight wide column">
          <%= paginate @profiles %>
        </div>
      </div>
  <% end %>


</div>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Platform:</strong>
  <%= @profile.platform_id %>
</p>

<p>
  <strong>Card holder name:</strong>
  <%= @profile.card_holder_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile.email %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @profile.photo %>
</p>

<p>
  <strong>Photo upload allowed:</strong>
  <%= @profile.photo_upload_allowed %>
</p>

<p>
  <strong>Card number:</strong>
  <%= @profile.card_number %>
</p>

<p>
  <strong>Valid from:</strong>
  <%= @profile.valid_from %>
</p>

<p>
  <strong>Valid to:</strong>
  <%= @profile.valid_to %>
</p>

<p>
  <strong>Is profile present on ccdb:</strong>
  <%= @profile.is_profile_present_on_ccdb %>
</p>
<p>
  <strong>Report Version:</strong>
  <%= @profile.report.version %>
</p>

<%= link_to 'Back', report_profiles_path(params[:report_id]) %>