config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home'

  mount Sidekiq::Web => '/jobs'

  get 'reports/index'

  get 'reports/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "reports#index"

  get "/profiles/report", "profiles#report"

  resources :reports, only: [:index, :show, :destroy] do
    resources :profiles, only: [:index, :show]
    get 'summary', on: :member
  end

  resources :analytics_events do
    post 'fire', on: :member
  end


  post 'import-report', to: 'reports#import'
  post 'import-analytics-logfile', to: 'analytics_events#import_analytics_logfile'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/analytics_event.rb
class AnalyticsEvent < ApplicationRecord

  def fire!(opts = {})
    logger.tagged "Firing #{id}" do
      platforms = opts[:only] || [:belladati, :firehose, :kinesis]

      AnalyticsEvent.transaction do
        fire_to_belladati if platforms.include? :belladati
        fire_to_kinesis_stream if platforms.include? :kinesis

        self.update! fired: true
      end
    end
  end

  def fire_to_firehose(opts={})
    FirehoseClient.put_record(
          delivery_stream_name: opts[:delivery_stream_name] || 'mw-stream-s3',
          record: {
            data: "#{self.to_json}\n"
          }
        )

    logger.debug "Streamed to Firehose #{self.id} event"
  end

  def fire_to_kinesis_stream
    client = Aws::Kinesis::Client.new
    client.put_record partition_key: self.id.to_s, stream_name: 'mw-stream', data: "#{self.to_json}\n"

    logger.debug "Streamed to Kinesis #{self.id} event"
  end

  def to_belladati_json(opts = {})
    attrs = public_attributes
    attrs.slice!(*opts[:only]) if opts[:only].present?

    attrs = attrs.transform_keys do |k|
      if k != 'id'
       "L_#{k.upcase}"
     else
       k
     end
    end

    attrs.transform_values! &:to_s

  end

  def from_log_line(log_line = '')
    Time.use_zone('UTC') do
      ll = log_line.split('|').map { |x| x == "null" ? nil : x }
      latlon = ll[1]&.gsub('latitude=', '')&.gsub('longitude=', '')&.gsub('LatLon', '')&.gsub(' ', '')&.gsub('(', '')&.gsub(')', '')

      self.assign_attributes(
        datetime: Time.zone.strptime(ll[0], '%H:%M:%S_%d%m%Y'),
        latitude: latlon&.split(',')&.first,
        longitude: latlon&.split(',')&.second,
        user_agent: ll[2]&.strip,
        ip: ll[3]&.strip,
        country_id: ll[4]&.strip,
        institute_id: ll[5]&.strip,
        language: ll[6]&.strip,
        app_version: ll[7]&.strip,
        user_id: ll[8]&.strip,
        card_id: ll[9]&.strip,
        ccdb_card_id: ll[10]&.strip,
        session_id: ll[11]&.strip,
        action_type_code: ll[12]&.strip,
        action_params: ll[13]&.strip,
      )
    end

    self
  end

  # Sample
  # 00:02:55_11012018|LatLon(latitude=-45.03023, longitude=168.66271)|iOS|125.239.128.28|null|null|en|3.11|103195|103422|24162055|1697580|0302|
  # 10:55:46_07082017|48.85341,2.3488|Android|82.12.182.192|2635167|67|en|3.6|22180|22088|21783491|987480|0302|
  class << self

    def import_log_file(fname, each = 2)
      events = []
      @@lines ||= File.readlines(fname)
      @@lines.each_with_index do |line, idx|
        events << AnalyticsEvent.new.from_log_line(line)

        if idx % each == 0
          self.import events, validate: false
          logger.info "Processed #{idx} events..."
          events = []
        end
      end

      self.import events, validate: false
    end

    def stream_events(opts ={})
      eps = opts[:eps] || 1
      idx = 1
      logger.tagged "Stream" do

        count = AnalyticsEvent.where.not(latitude: nil).where.not(fired: true).count
        events = AnalyticsEvent
          .where.not(latitude: nil)
          .where.not(fired: true)
          .offset((SecureRandom.random_number(0..0.7)*count).to_i)
          .order(datetime: :asc)
        logger.info "Found #{count} events to stream"

        events.each do |e|
          Thread.new do
            logger.debug "Streaming idx #{idx += 1}"
            e.fire! only: [:kinesis]
          end
          delay = 1.0/eps
          jitter = SecureRandom.random_number(0.7..1.3)
          sleep delay * jitter
        end

        logger.info "Dispatched all events"
      end
    end


    def fire_list!(events = [], opts = {})
      cols = ['ccdb_card_id', 'ip', 'language', 'session_id', 'user_id']

      events.map! { |e| e.to_belladati_json(only: cols) }

      dict = {
        columns: cols.map! { |c| { code: "L_#{c.upcase}" } },
        data: events.map(&:values),
      }
      dict = dict.to_json

      token = AnalyticsEvent.new.belladati_auth_token

      uri = URI.parse("https://service.belladati.com/api/import/33808?oauth_consumer_key=#{Rails.application.secrets[:belladati_oauth_consumer_key]}&oauth_token=#{token}&oauth_timestamp=#{Time.now.to_i}&oauth_nonce=#{SecureRandom.uuid}")
      request = Net::HTTP::Post.new(uri)
      request.content_type = "application/octet-stream"
      request.body = dict

      req_options = {
        use_ssl: uri.scheme == "https",
      }

      response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
        http.request(request)
      end
      "BD Response: #{response.body}"
    end

    def import_log_line(log_line = '')
      AnalyticsEvent.new.from_log_line(log_line).save!
    end
  end


  def public_attributes
    attrs = attributes.except 'created_at', 'updated_at', 'fired', 'uuid', 'id'
    attrs['location'] = "#{latitude},#{longitude}"
    attrs
  end


  def fire_to_belladati
    logger.info "Firing #{self.id} to belladati..."
    logger.debug "Streaming #{self.to_belladati_json}..."
    uri = URI.parse("https://service.belladati.com/api/dataSets/33808/data")
    request = Net::HTTP::Post.new(uri)
    request.content_type = "application/x-www-form-urlencoded"
    request.set_form_data(
      "oauth_consumer_key" => Rails.application.secrets[:belladati_oauth_consumer_key],
      "oauth_nonce" => "#{SecureRandom.uuid}",
      "oauth_timestamp" => "#{Time.now.to_i}",
      "oauth_token" => belladati_auth_token,
      "dataRow" => self.to_belladati_json.to_json,
    )

    req_options = {
      use_ssl: uri.scheme == "https",
    }

    response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
      http.request(request)
    end

    logger.info "Fired #{self.id} to Belladati. Response #{response.code} #{response.body}"
  end

  def belladati_auth_token
    token = Rails.cache.fetch('belladati-auth-token', expires_in: 5.minutes) do
      logger.warn "Requesting auth token from Belladati..."
      require 'net/http'
      require 'uri'

      uri = URI.parse("https://service.belladati.com/oauth/accessToken")
      request = Net::HTTP::Post.new(uri)
      request.content_type = "application/x-www-form-urlencoded"
      request.set_form_data(
        "oauth_consumer_key" => Rails.application.secrets[:belladati_oauth_consumer_key],
        "oauth_nonce" => "#{SecureRandom.uuid}",
        "oauth_timestamp" => "#{Time.now.to_i}",
        "x_auth_username" => Rails.application.secrets[:belladati_xauth_username],
        "x_auth_password" => Rails.application.secrets[:belladati_xauth_password],
      )

      req_options = {
        use_ssl: uri.scheme == "https",
      }

      response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
        http.request(request)
      end

      response.body.split('&').first.split('=').last
    end
    logger.info "Auth Token: #{token}"

    token
  end

  private

end

app/controllers/analytics_events_controller.rb
class AnalyticsEventsController < ApplicationController
  before_action :set_analytics_event, only: [:show, :edit, :update, :fire, :destroy]
  around_action :wrap_transaction, only: [:import_analytics_logfile]

  # GET /analytics_events
  # GET /analytics_events.json
  def index
    @q = AnalyticsEvent.ransack params[:q]
    @analytics_events = @q.result.page params[:page]
  end

  # GET /analytics_events/1
  # GET /analytics_events/1.json
  def show
  end

  # GET /analytics_events/new
  def new
    @analytics_event = AnalyticsEvent.new
  end

  # GET /analytics_events/1/edit
  def edit
  end

  def fire
    @analytics_event.fire!
    flash[:success] = "Event id #{@analytics_event.id} from #{@analytics_event.datetime} fired"
    redirect_to analytics_events_path

  end


  def import_analytics_logfile
    logger.info "Importing analytics logfile"
    begin
      idx = 0
      File.readlines(params[:import_file].tempfile).each do |line|
        AnalyticsEvent.import_log_line line
        logger.info "Imported #{idx} events" if idx % 100 == 0
      end

      flash[:success] = "Events imported."

    rescue StandardError => error
      flash[:error] = "There was an error importing: #{error.message}"
      raise error
    ensure
      redirect_to analytics_events_path
    end
  end

  # POST /analytics_events
  # POST /analytics_events.json
  def create
    @analytics_event = AnalyticsEvent.new(analytics_event_params)

    respond_to do |format|
      if @analytics_event.save
        format.html { redirect_to @analytics_event, notice: 'Analytics event was successfully created.' }
        format.json { render :show, status: :created, location: @analytics_event }
      else
        format.html { render :new }
        format.json { render json: @analytics_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /analytics_events/1
  # PATCH/PUT /analytics_events/1.json
  def update
    respond_to do |format|
      if @analytics_event.update(analytics_event_params)
        format.html { redirect_to @analytics_event, notice: 'Analytics event was successfully updated.' }
        format.json { render :show, status: :ok, location: @analytics_event }
      else
        format.html { render :edit }
        format.json { render json: @analytics_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analytics_events/1
  # DELETE /analytics_events/1.json
  def destroy
    @analytics_event.destroy
    respond_to do |format|
      format.html { redirect_to analytics_events_url, notice: 'Analytics event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_analytics_event
      @analytics_event = AnalyticsEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def analytics_event_params
      params.fetch(:analytics_event, {})
    end

    def wrap_transaction
      AnalyticsEvent.transaction { yield }
    end
end

app/helpers/analytics_events_helper.rb
module AnalyticsEventsHelper
end

app/views/analytics_events/_analytics_event_row.html.erb
<tr>
  <% (analytics_event.attribute_names - discard_fields).each do |an| %>
  <td>
    <%= analytics_event.send(an) %>
  </td>

  <% end %>
  <td>
    <% if analytics_event.fired %>
      Already fired
    <% else %>
      <%= link_to 'Fire!', fire_analytics_event_path(analytics_event), method: :post %>
    <% end %>
  </td>
</tr>

app/views/analytics_events/_form.html.erb
<%= form_with(model: analytics_event, local: true) do |form| %>
  <% if analytics_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(analytics_event.errors.count, "error") %> prohibited this analytics_event from being saved:</h2>

      <ul>
      <% analytics_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/analytics_events/_search_form_analytics.html.erb
<div class="ui raised segment">

  <%= search_form_for(@q, url: analytics_events_path,class: "ui form") do |f| %>


        <div class="field">
          <%= f.label 'Free text search' %>
          <%= f.search_field :action_type_code_or_user_id_or_location_or_ip_or_language_or_app_version_or_card_id_or_ccdb_card_id_or_session_id_or_action_params_cont %>
        </div>

      <%= f.submit class: "ui primary button" %> <span><%= @q.result.count %> events found</span>
  <% end %>
</div>

app/views/analytics_events/edit.html.erb
<h1>Editing Analytics Event</h1>

<%= render 'form', analytics_event: @analytics_event %>

<%= link_to 'Show', @analytics_event %> |
<%= link_to 'Back', analytics_events_path %>

app/views/analytics_events/index.html.erb
<% cache [@analytics_events.last, request.params.keys.join('-'), request.params.values.join('-')] do %>
  <p id="notice"><%= notice %></p>

  <h1>Analytics Events</h1>

  <div class="ui segment">
    <%= form_with(url: import_analytics_logfile_path, html: {multipart: true}, class: "ui form") do |form| %>
    <div class="field">
      <%= form.label "Import Log File with events from EC2 Instances" %>
    </div>

    <div class="field">
      <%= form.file_field :import_file, class: "ui button" %>
    </div>
    <%= form.submit "Upload...", class: "ui button", data: {disable_with: "Processing, may take a while..."} %>
  <% end %>
</div>

<div class="ui grid">

  <div class="centered row">
    <div class="eight wide column">
      <%= paginate @analytics_events %>
    </div>
  </div>

  <div class="centered row">
    <div class="nine wide column">
      <div class="nine wide column">
        <%= render 'analytics_events/search_form_analytics' %>
      </div>
    </div>

  </div>

  <% discard_fields = ['created_at', 'updated_at', 'id', 'fired', 'uuid'] %>
    <div class="row">
      <div class="sixteen wide column">

        <table class="ui celled striped table">
          <thead>
            <tr>
              <% (AnalyticsEvent.attribute_names - discard_fields).each do |an|%>
                <th>
                  <%= sort_link(@q, an.to_sym) %>
                </th>
              <% end %>

              <th colspan="1">Actions</th>
            </tr>
          </thead>

          <tbody>
            <%= render collection: @analytics_events, partial: 'analytics_events/analytics_event_row', cache: true, as: 'analytics_event', locals: { discard_fields: discard_fields } %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="centered row">
      <div class="eight wide column">
        <%= paginate @analytics_events %>
      </div>
    </div>

  </div>

  <br>

  <%= link_to 'New Analytics Event', new_analytics_event_path %>
<% end %>

app/views/analytics_events/new.html.erb
<h1>New Analytics Event</h1>

<%= render 'form', analytics_event: @analytics_event %>

<%= link_to 'Back', analytics_events_path %>

app/views/analytics_events/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_analytics_event_path(@analytics_event) %> |
<%= link_to 'Back', analytics_events_path %>