config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home'

  mount Sidekiq::Web => '/jobs'

  get 'reports/index'

  get 'reports/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "reports#index"

  get "/profiles/report", "profiles#report"

  resources :reports, only: [:index, :show, :destroy] do
    resources :profiles, only: [:index, :show]
    get 'summary', on: :member
  end

  resources :analytics_events do
    post 'fire', on: :member
  end


  post 'import-report', to: 'reports#import'
  post 'import-analytics-logfile', to: 'analytics_events#import_analytics_logfile'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  has_many :profiles, dependent: :destroy

  def diff_report(limit = 0)
    differences_count = profiles.count/2
    logger.info "There are #{differences_count} different profiles"

    orphans = profiles.where(profile_id: nil)
    logger.info "#{orphans.count} do not have a matching profile in the other platform"

    fields = different_fields(limit)
    logger.info "Fields differing: #{fields.inspect}"
    logger.info ap(fields)

    character_distribution = character_distribution()

    {
        fields: fields,
        differences_count: differences_count,
        orphans: orphans.count,
        character_distribution: character_distribution
    }
  end


  def different_fields(limit)
    the_limit = limit.zero? ? 10_000_000 : limit
    siblings = profiles.where(platform_name: 'mw')
                   .includes(:sibling)
                   .order(created_at: :asc)
                   .limit(the_limit)
                   .map do |profile|
      profile.sibling_difference.map {|key, _| {key => 1}}.reduce(:merge)
    end

    reduced = siblings.reduce do |x, y|
      # logger.debug "\nReducing #{x.inspect} and #{y.inspect}"
      first = x || {}
      second = y || {}

      second.merge(first) {|key, old, new| new + old}
    end

    sorted = reduced.sort {|x, y| y[1] <=> x[1]}

  end

  def character_distribution
    [:mw, :ccdb].map do |platform|
      {
          platform => profiles.where(platform_name: platform)
                          .pluck(:card_number)
                          .map {|c| c.length}
                          .reduce do |a, b|
            item = a.is_a?(Hash) ? a : {a => 1}
            item.merge(item.dig(b).nil? ? {b => 1} : {b => item[b] + 1})
          end
      }
    end.reduce(&:merge)

  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  http_basic_authenticate_with name: Rails.application.secrets.basic_auth_username, password: Rails.application.secrets.basic_auth_password
  before_action :set_report, only: [:show, :destroy, :summary]

  def index
    @reports = Report.all.order(version: :desc)
  end

  def show
  end

  def destroy
    @report.destroy
  end

  def summary
    key = @report

    @summary = Rails.cache.fetch(key, expires_in: 30.seconds) do
      logger.info "Cache miss. Retrieving report..."
      @report.diff_report
    end
  end

  def import
    begin
      text = params[:import_file].read
      json = JSON.parse(text)
      Profile.import_json(json, true)
      report = Report.last
      flash[:success] = "Report imported. Version: #{report.version}. Profiles: #{report.profiles.count/2}"

    rescue StandardError => error
      flash[:error] = "There was an error importing: #{error.inspect}"
    ensure
      redirect_to reports_path
    end

  end

  private

  def set_report
    @report = Report.find(params[:id])
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.erb
<div class="ui grid">
  <div class="row">
    <div class="three wide left aligned left floated column">
      <h1>Reports</h1>
    </div>

    <div class="five wide right aligned right floated column">
      <div class="ui segment">
        <%= form_with(url: import_report_path, html: {multipart: true}, class: "ui form") do |form| %>
            <div class="field">
              <%= form.label "Import JSON report file" %>
            </div>

            <div class="field">
              <%= form.file_field :import_file, class: "ui button" %>
            </div>
            <%= form.submit "Upload...", class: "ui button", data: {disable_with: "Processing, may take a while..."} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="ui center aligned celled four column grid">
  <div class="row">
    <div class="column"><strong>Report version</strong></div>
    <div class="column"><strong>Differences</strong></div>
    <div class="column"><strong>Approx. Date (UTC)</strong></div>
    <div class="column"></div>
  </div>

  <% @reports.each do |report| %>
      <div class="row">
        <div class="column"><%= report.version %></div>
        <div class="column"><%= report.count %></div>
        <div class="column"><%= report.date&.to_formatted_s(:long) %></div>
        <div class="column">
          <div class="ui buttons">
            <%= link_to "Summary", summary_report_path(report), class: "ui button" %>
            <%= link_to("View profiles", report_profiles_path(report), class: "ui primary button") %>
            <%= link_to("Destroy", report_path(report), class: "ui negative button", method: :delete, data: {confirm: "Are you sure you want to destroy the report #{report.version}???!!!"}) %>
          </div>
        </div>
      </div>
  <% end %>

</div>
  

app/views/reports/show.html.erb
<h1>Reports#show</h1>
<p>Find me in app/views/reports/show.html.erb</p>

app/views/reports/summary.html.erb
<div class="ui segment">

  <strong>Field count difference</strong>: <%= @summary[:differences_count] %>
  <br/>
  <strong>Number of orphans (profile only in one platform): <%= @summary[:orphans] %></strong>
  <table class="ui sortable celled table">
    <thead>
    <tr>
      <th class="">Field</th>
      <th class="sorted ascending">Differences</th>
    </tr>
    </thead>

    <tbody>

    <% @summary[:fields].each do |field| %>
        <tr>
          <td class="">
            <a class="ui <%= field_color_for(field[0]) %> label"><%= field[0].to_s.humanize %></a>
          </td>
          <td class=""><%= field[1].to_s %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <br/>

</div>

<% @summary[:character_distribution]&.each do |cd| %>
    <table class="ui sortable celled table">
      <thead>
      <tr>
        <th class=""><%= cd[0] %>: Number of characters in card number</th>
        <th class="sorted ascending">Number of profiles</th>
      </tr>
      </thead>
      <tbody>
      <% cd[1].keys.each do |key| %>
          <tr>
            <td class=""><%= key.to_s %> characters</td>
            <td class=""><%= cd[1][key].to_s %> profiles</td>
          </tr>
      <% end %>
      </tbody>


    </table>

<% end %>